
int Ysize
create Y[]
"456.txt" 0 file.text.open drop
0 Y[] file.text.fx to Ysize
Ysize cells allot
Ysize .

CREATE DY[] Ysize cells allot

100 CONSTANT DATASIZE

CREATE X[] DATASIZE FLOATS ALLOT

int data[]
x[] to data[]
INT SIZE
YSIZE TO SIZE


INT WINDOW
10 TO WINDOW
INT TIME

50 TO TIME

FLOAT SIGMA
FLOAT SIGMA0
FLOAT EPSILON

1.0 SIGMA0 F!
0.1 EPSILON F!

FLOAT X0

PROC P(X) // F:X-- F: P
  X0 F!
  0.0
  WINDOW 0 DO
    DATA[] TIME I - -TH F@ X0 F@ F-
    I S>F EPSILON F@ F* SIGMA0 F@ F+ SIGMA F!
    SIGMA F@ FGAUSS
    SIGMA F@ F/
    F+
  LOOP
ENDPROC

PROC FILLCONST
  DATASIZE 0 DO
    1.0 X[] I -TH F!
    I 50 > IF 2.0 X[] I -TH F! THEN
  LOOP
ENDPROC

FILLCONST

FLOAT XMIN
FLOAT XMAX
FLOAT XSTEP
INT STEPS

FLOAT PMAX
FLOAT ARGMAX


PROC FINDX
  XMAX F@ XMIN F@ F- STEPS S>F F/ XSTEP F!
  0.0 PMAX F!
  XMIN F@ ARGMAX F!
  XMIN F@ X0 F!
  STEPS 0 DO
    X0 F@ P(X) FDUP PMAX F@ F> IF
      FDUP PMAX F! X0 F@ ARGMAX F!
    THEN FDROP
    X0 F@ XSTEP F@ F+ X0 F!
  LOOP

ENDPROC

0.0 XMIN F!
5.0 XMAX F!
1000 TO STEPS

0 CHART.SHOW
0 0 1000 500 0 CHART.RECT

0 0 CHART.ADDSERIES
3 0 SERIES.LINEWIDTH
1 0 CHART.ADDSERIES
3 1 SERIES.LINEWIDTH
0x00FF00 1 SERIES.COLOR
2 0 CHART.ADDSERIES
3 2 SERIES.LINEWIDTH
0xFF0000 2 SERIES.COLOR

3 0 CHART.ADDSERIES
5 3 SERIES.LINEWIDTH
0x00FF 3 SERIES.COLOR



1 CHART.SHOW
0 500 1000 300 1 CHART.RECT
20 1 CHART.ADDSERIES
21 1 CHART.ADDSERIES
0x00FF 21 SERIES.COLOR

FLOAT DY2
FLOAT DY^2

PROC SHOWD/DT
  20 SERIES.CLEAR
  0.0 DY2 F!
  SIZE 1 DO
    I S>F
    DATA[] I -TH F@
    DATA[] I 1 - -TH F@ F-
    FDUP FDUP F* DY2 F@ F+ DY2 F!
    20 SERIES.FXY
  LOOP
ENDPROC

INT GRAPH
0 TO GRAPH

FLOAT ARGMAX1


PROC AVERAGE
  GRAPH SERIES.CLEAR
  SIZE WINDOW DO
     I TO TIME
     0.0
     WINDOW 0 DO
       X[] TIME I - -TH F@ F+
     LOOP
     WINDOW S>F F/
     I S>F FSWAP GRAPH SERIES.FXY
  LOOP
ENDPROC

PROC RUN
  GRAPH SERIES.CLEAR
  21 SERIES.CLEAR
  0.0 DY^2 F!
  SIZE WINDOW DO
     I TO TIME
     FINDX
     I S>F ARGMAX F@ GRAPH SERIES.FXY
     I S>F
     ARGMAX F@ ARGMAX1 F@ F- I WINDOW = IF FDROP 0.0 THEN
     FDUP
     FDUP F* DY^2 F@ F+ DY^2 F!
     21 SERIES.FXY
     ARGMAX F@ ARGMAX1 F!
  LOOP
ENDPROC


// ARRAY_FMIN : begin // addr, n -- index_min, f: min

Y[] TO DATA[]

DATA[] SIZE [FMIN] XMIN F! DROP
DATA[] SIZE [FMAX] XMAX F! DROP

100 TO STEPS

DATA[] SIZE 0 series.plotfx

0.001 EPSILON F!
1 TO GRAPH
RUN

0.1 EPSILON F!
2 TO GRAPH
RUN

SHOWD/DT

DY2 F@ F.
DY^2 F@ F.


