
INT DSIZE

CREATE Y[]

"delta_ticks.txt" 0 file.text.open drop
0 Y[] file.text.x to DSIZE
0 FILE.TEXT.CLOSE DROP

DSIZE CELLS ALLOT


CREATE X[] DSIZE CELLS ALLOT

PROC FILL-LINEAR
  DSIZE 0 DO
    I S>F
    X[] I -TH F!
    Y[] I -TH @ S>F
    Y[] I -TH F!
  LOOP
ENDPROC

FILL-LINEAR

VARIABLE PHI
VARIABLE RR
VARIABLE PX
VARIABLE PY
VARIABLE SIGMA 25.0 SIGMA F!

INT DSTEP 1 TO DSTEP
INT T0 0 TO T0
INT TMAX DSIZE TO TMAX

PROC P(PHI,R)
  0.0
  TMAX T0 DO
     X[] I -TH F@ PY F@ F*
     Y[] I -TH F@ PX F@ F* F-
     RR F@ F+
     SIGMA F@ FGAUSS
     F+
  DSTEP +LOOP
ENDPROC

VARIABLE PHI0
VARIABLE PHI+
INT PHISTEPS


VARIABLE R0
VARIABLE R+
INT RSTEPS

: >RAD PI F* 180.0 F/ ;

400 TO PHISTEPS
-2.0 >RAD PHI0 F!
PHI0 F@ 2.0 F* FABS PHISTEPS S>F F/
PHI+ F!

200 TO RSTEPS
-500.0 R0 F!
5.0 R+ F!

VARIABLE PT
VARIABLE PMAX
VARIABLE PHIARGMAX
VARIABLE RARGMAX

0 CHART.SHOW

0 CHART.ALIGN.CLIENT
0 0 CHART.ADDSERIES
1 0 CHART.ADDSERIES

PROC LOOP_PHIR
  0.0 PMAX F!
  0.0 PHIARGMAX F!
  0.0 RARGMAX F!
  RSTEPS 0 DO
    R0 F@ I S>F R+ F@ F* F+ RR F!
    PHISTEPS 0 DO
      PHI0 F@ PHI+ F@ I S>F F* F+ PHI F!
      PHI F@ FCOS PX F!
      PHI F@ FSIN PY F!
      P(PHI,R) PT F!
      PT F@ PMAX F@ F> IF
        PT F@ PMAX F!
        PHI F@ PHIARGMAX F!
        RR F@ RARGMAX F!
      THEN
    LOOP
  LOOP
ENDPROC

PROC PHI()
    PHISTEPS 0 DO
      PHI0 F@ PHI+ F@ I S>F F* F+ PHI F!
      PHI F@ FCOS PX F!
      PHI F@ FSIN PY F!
      P(PHI,R) PT F!
      PT F@ PMAX F@ F> IF
        PT F@ PMAX F!
        PHI F@ PHIARGMAX F!
        RR F@ RARGMAX F!
      THEN
    LOOP
ENDPROC


PROC T
  RSTEPS 0 DO
    I S>F 50.0 F- RR F!
    RR F@ F. CR
    PHI()
  LOOP
ENDPROC


PROC FILL-TEST
  DSIZE 0 DO
    I S>F X[] I -TH F!
    I S>F Y[] I -TH F!
  LOOP
ENDPROC

PROC DRAW
  0 SERIES.CLEAR
  1 SERIES.CLEAR
  DSIZE 0 DO
    X[] I -TH F@
    Y[] I -TH F@
    0 SERIES.FXY
  LOOP

  // Y = (Py*x + R)/pX

  T0 1 - S>F
  FDUP
  PHIARGMAX F@ FSIN F* RARGMAX F@ F+
  PHIARGMAX F@ FCOS F/
  1 SERIES.FXY

  TMAX 1 - S>F
  FDUP
  PHIARGMAX F@ FSIN F* RARGMAX F@ F+
  PHIARGMAX F@ FCOS F/
  1 SERIES.FXY

ENDPROC

0x0000FF 1 SERIES.COLOR
5 1 SERIES.LINEWIDTH

CR
"SIZE= " PRINT dsize .

// FILL-TEST

PROC RUN
  0x00FF00 0 SERIES.COLOR
  DRAW
  1 SERIES.CLEAR

  16 0 DO
    I 5000 * TO T0
    I 1 + 5000 * TO TMAX
    100 TO DSTEP

    LOOP_PHIR

    T0 1 - S>F
    FDUP
    PHIARGMAX F@ FSIN F* RARGMAX F@ F+
    PHIARGMAX F@ FCOS F/
    1 SERIES.FXY

    TMAX 1 - S>F
    FDUP
    PHIARGMAX F@ FSIN F* RARGMAX F@ F+
    PHIARGMAX F@ FCOS F/
    1 SERIES.FXY

  LOOP
ENDPROC

25000 TO T0
30000 TO TMAX

50 TO DSTEP



CR
"R= " PRINT RARGMAX F@ F. CR
"PHI= " PRINT PHIARGMAX F@ F.
" " PRINT PHIARGMAX F@ PI F/ 180.0 F* F.

RUN

