

VARIABLE RX
VARIABLE RY
VARIABLE RZ
15.0 RX F!
195.0 RY F!
-135.0 RZ F!

50 CONSTANT XS
50 CONSTANT YS

: EXTENTX 0.8 ;
: EXTENTY 0.8  ;

: STEPX EXTENTX XS S>F F/ ;
: STEPY EXTENTY YS S>F F/ ;

CREATE Z[] XS YS * CELLS ALLOT

: INIT-Z
  YS 0 DO
    XS 0 DO
      0.8
      I XS 2 / - S>F FDUP F*
      J YS 2 / - S>F FDUP F* F+ 0.01 F* FEXP F/
      Z[] IJ -TH F!
    LOOP
  LOOP
;
INIT-Z


: RUNOPENGL3D

  OPENGL.MATRIX.MODELVIEW
  -1.0 1.0 -1.0 1.0 -1.0 1.0 OPENGL.ORTHO
  OPENGL.LOADIDENTITY

  1.0 1.0 1.0 1.0 OPENGL.CLEARCOLOR

  OPENGL.CLEAR

  OPENGL.FRONT.CW

  OPENGL.PUSHMATRIX

  RX F@ 0.0 0.0 1.0 OPENGL.ROTATEF
  RY F@ 0.0 1.0 0.0 OPENGL.ROTATEF
  RZ F@ 1.0 0.0 0.0 OPENGL.ROTATEF

  3.0 OPENGL.LINEWIDTH

  0.9 0.0 0.0 OPENGL.COLOR3F
  OPENGL.LINE
    0.0 0.0 0.0  OPENGL.VERTEX3D
    0.8 0.0 0.0  OPENGL.VERTEX3D
  OPENGL.END

  0.0 0.9 0.0 OPENGL.COLOR3F
  OPENGL.LINE
    0.0 0.0 0.0  OPENGL.VERTEX3D
    0.0 0.8 0.0  OPENGL.VERTEX3D
  OPENGL.END

  0.0 0.0 0.9 OPENGL.COLOR3F
  OPENGL.LINE
    0.0 0.0 0.0  OPENGL.VERTEX3D
    0.0 0.0 0.8  OPENGL.VERTEX3D
  OPENGL.END

  0.9 0.9 0.0 OPENGL.COLOR3F

  1.0 OPENGL.LINEWIDTH
  YS 1 - 0 DO
    XS 1 - 0 DO

      0.9 0.9 0.9 OPENGL.COLOR3F
      OPENGL.QUAD
        I S>F STEPX F*
        J  S>F STEPY F*
        Z[] J XS * I + -TH F@
        OPENGL.VERTEX3D
        I S>F STEPX F*
        J 1 + S>F STEPY F*
        Z[] J 1 + XS * I +  -TH F@
        OPENGL.VERTEX3D
        I 1 + S>F STEPX F*
        J 1 + S>F STEPY F*
        Z[] J 1 + XS * I + 1 + -TH F@
        OPENGL.VERTEX3D
        I 1 + S>F STEPX F*
        J  S>F STEPY F*
        Z[] J XS * I + 1 + -TH F@
        OPENGL.VERTEX3D
      OPENGL.END

      0.0 0.0 0.0 OPENGL.COLOR3F
      OPENGL.LINE
        I S>F STEPX F*
        J  S>F STEPY F*
        Z[] J XS * I + -TH F@ 0.001 F+
        OPENGL.VERTEX3D
        I S>F STEPX F*
        J 1 + S>F STEPY F*
        Z[] J 1 + XS * I +  -TH F@  0.001 F+
        OPENGL.VERTEX3D
      OPENGL.END

      OPENGL.LINE
        I S>F STEPX F*
        J S>F STEPY F*
        Z[] J XS * I + -TH F@  0.001 F+
        OPENGL.VERTEX3D
        I 1 + S>F STEPX F*
        J S>F STEPY F*
        Z[] J XS * I + 1 + -TH F@  0.001 F+
        OPENGL.VERTEX3D
      OPENGL.END


    LOOP
  LOOP


  OPENGL.POPMATRIX

;

: X- RX F@ 15.0 F- RX F! OPENGL3D OPENGL.UPDATE ;
: X+ RX F@ 15.0 F+ RX F! OPENGL3D OPENGL.UPDATE ;
: Y- RY F@ 15.0 F- RY F! OPENGL3D OPENGL.UPDATE ;
: Y+ RY F@ 15.0 F+ RY F! OPENGL3D OPENGL.UPDATE ;
: Z- RZ F@ 15.0 F- RZ F! OPENGL3D OPENGL.UPDATE ;
: Z+ RZ F@ 15.0 F+ RZ F! OPENGL3D OPENGL.UPDATE ;

OPENGL.SHOW
100 0 1000 800 OPENGL.RECT
USE RUNOPENGL3D TO OPENGL3D

0 BUTTON.SHOW
0 0 100 40 0 BUTTON.RECT
"X-" 0 BUTTON.TEXT
"X-" 0 BUTTON.ACTION

1 BUTTON.SHOW
0 50 100 40 1 BUTTON.RECT
"X+" 1 BUTTON.TEXT
"X+" 1 BUTTON.ACTION

2 BUTTON.SHOW
0 100 100 40 2 BUTTON.RECT
"Y-" 2 BUTTON.TEXT
"Y-" 2 BUTTON.ACTION

3 BUTTON.SHOW
0 150 100 40 3 BUTTON.RECT
"Y+" 3 BUTTON.TEXT
"Y+" 3 BUTTON.ACTION


4 BUTTON.SHOW
0 200 100 40 4 BUTTON.RECT
"Z-" 4 BUTTON.TEXT
"Z-" 4 BUTTON.ACTION

5 BUTTON.SHOW
0 250 100 40 5 BUTTON.RECT
"Z+" 5 BUTTON.TEXT
"Z+" 5 BUTTON.ACTION



